name: DPT Software Backend

on:
  push:
    branches: [ master ]  

jobs:
   
  deploy:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:

          host: ${{ secrets.WAPPNET_SERVER }}

          key: ${{ secrets.WAPPNET_KEY }}

          username: ${{ secrets.WAPPNET_USER }}

          script: |
            
            cd /var/www/html/dpt_software_backend/
            
            (php artisan down --message 'The app is being (quickly!) updated. Please try again in a minute.') || true
                # Update codebase
                git fetch origin master
                git reset --hard origin/master
                # Install dependencies based on lock file
                composer install --no-interaction --prefer-dist --optimize-autoloader
               
                # Migrate database
                php artisan migrate
                php artisan tenancy:migrate
                
                if [ -e deploy.sh ]
                then
                        chmod 777 deploy.sh
                    ./deploy.sh
                fi
                
                # Note: If you're using queue workers, this is the place to restart them.
                # ...
                # Clear cache
                php artisan optimize:clear
                php artisan cache:clear
                # php artisan optimize
                # Reload PHP to update opcache
                #echo "" | -S service php7.4-fpm reload
            # Exit maintenance mode
            php artisan up
            echo "Application deployed!"
